image:
  name: registry.gitlab.com/mesonomics/meso-alert/play-server
  entrypoint: [""]

scalatest:
  stage: test
  script:
    - make sbt-test

deploy:
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config get-contexts
    - kubectl config use-context mesonomics/meso-alert:meso-alert-k8agent
    - kubectl get pods
  only:
    - master