stages:
  - build
  - test
  - push
  - deploy

image:
  name: registry.gitlab.com/mesonomics/meso-alert/ci
  entrypoint: [""]

scalatest:
  stage: test
  script:
    - make sbt-test

docker:
  stage: push
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - export PLAY_SECRET=changeme
    - make -e sbt-build
    - cd docker
    - docker-compose up --no-start --build
    - cd ..
    - docker push registry.gitlab.com/mesonomics/meso-alert/play-server
  only:
    - master

k8:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config get-contexts
    - kubectl config use-context mesonomics/meso-alert:meso-alert-k8agent
    - kubectl apply -f k8/deployment.yaml
    - kubectl apply -f k8/service.yaml
  only:
    - master
