stages:
  - build
  - test
  - push
  - deploy

image:
  name: registry.gitlab.com/mesonomics/meso-alert/ci
  entrypoint: [""]

scalatest:
  stage: test
  script:
    - make sbt-test

scalafix:
  stage: test
  script:
    - make sbt-scalafix-check

docker:
  stage: push
  script:
    - echo "POSTGRES_PORT=5432" > docker/.env
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - make -e sbt-build
    - cd docker
    - docker-compose up --no-start --build meso-alert
    - cd ..
    - docker push registry.gitlab.com/mesonomics/meso-alert/play-server
  only:
    - master

k8:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config use-context mesonomics/meso-alert:meso-alert-k8agent
    - kubectl apply -f k8/sealed-secrets.yaml
    - kubectl apply -f k8/web-application.yaml
    - kubectl apply -f k8/postgres.yaml
    - kubectl rollout restart deployment/meso-alert-deployment
  only:
    - master
