variables:
  VAULT_SERVER_URL: "https://vault-cluster.vault.03c4f565-02ef-4d3f-9f32-4447b76c5947.aws.hashicorp.cloud:8200"

stages:
  - build
  - test
  - push
  - deploy

image:
  name: registry.gitlab.com/mesonomics/meso-alert/ci
  entrypoint: [""]

scalatest:
  stage: test
  script:
    - make sbt-test

docker:
  secrets:
    POSTGRES_PASSWORD:
      vault: production/db/password@ops
  stage: push
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - export PLAY_SECRET=changeme
    - make -e sbt-build
    - cd docker
    - docker-compose up --no-start --build
    - cd ..
    - docker push registry.gitlab.com/mesonomics/meso-alert/play-server
  only:
    - master

k8:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config use-context mesonomics/meso-alert:meso-alert-k8agent
    - kubectl apply -f k8/web-application.yaml
    - kubectl apply -f k8/postgres.yaml
    - kubectl rollout restart deployment/meso-alert-deployment
  only:
    - master
