repos:
  -   repo: https://github.com/softwaremill/scala-pre-commit-hooks
      rev: v0.3.0
      default_phase: push #change to commit if desired
      hooks: #mix and match any of the following:
        -   id: sbt-scalafmt
