version: "3.3"

services:

  meso-alert:
    image: registry.gitlab.com/mesonomics/meso-alert/play-server
    container_name: meso-alert
    ports:
      - "9000:9000"
    build:
      context: ../
      dockerfile: ./docker/meso-alert.docker

  meso-alert-ci:
    image: registry.gitlab.com/mesonomics/meso-alert/ci
    container_name: meso-alert-ci
    build:
      context: ./
      dockerfile: meso-alert-ci.docker

  postgres-db:
    container_name: postgres-db
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: meso-alert
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: meso-alert
    volumes:
      - /data/1/meso-alert-db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
