version: "3.3"

services:

  meso-alert:
    image: registry.gitlab.com/mesonomics/meso-alert/play-server
    container_name: meso-alert
    ports:
      - "9000:9000"
    build:
      context: ../
      dockerfile: ./docker/meso-alert.docker
      args:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_PORT: ${POSTGRES_PORT}
        SODIUM_KEY: ${SODIUM_KEY}
        PLAY_KEY: ${PLAY_KEY}
        SLACK_CLIENT_ID: ${SLACK_CLIENT_ID}
        SLACK_CLIENT_SECRET: ${SLACK_CLIENT_SECRET}
        POSTGRES_HOST: ${POSTGRES_HOST}
        EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
        EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
        EMAIL_HOST: ${EMAIL_HOST}
        EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
        EMAIL_DESTINATION: ${EMAIL_DESTINATION}
        SLACK_DEPLOY_URL: ${SLACK_DEPLOY_URL}
        AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
        AUTH0_DOMAIN: ${AUTH0_DOMAIN}
        AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}

  meso-alert-ci:
    image: registry.gitlab.com/mesonomics/meso-alert/ci
    container_name: meso-alert-ci
    build:
      context: ./
      dockerfile: meso-alert-ci.docker

  meso-alert-backup:
    image: registry.gitlab.com/mesonomics/meso-alert/postgres-backup
    container_name: postgres-backup
    build:
      context: ./
      dockerfile: postgres-backup.docker

  postgres-db:
    container_name: postgres-db
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: meso-alert
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: meso-alert
    volumes:
      - /data/1/meso-alert-db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

