version: "3.3"

services:

  meso-alert:
    image: registry.gitlab.com/mesonomics/meso-alert/play-server
    container_name: meso-alert
    ports:
      - "9000:9000"
    build:
      context: ../
      dockerfile: ./docker/meso-alert.docker
      args:
        play_secret: ${PLAY_SECRET}

  meso-alert-ci:
    image: registry.gitlab.com/mesonomics/meso-alert/ci
    container_name: meso-alert-ci
    build:
      context: ./
      dockerfile: meso-alert-ci.docker

  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: meso-alert
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: meso-alert
      PGDATA: /data/fast/1/meso-alert
    volumes:
      - postgres-db-data:/data/fast/1/meso-alert
    ports:
      - "5436:5432"

volumes:
    postgres-db-data: