kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: meso-alert-postgres-pv-claim
  namespace: default
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: do-block-storage
