apiVersion: v1
kind: PersistentVolume
metadata:
  name: meso-alert-postgres-pv
  labels:
    type: local
spec:
  storageClassName: do-block-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
