apiVersion: apps/v1
kind: Deployment
metadata:
  name: meso-alert-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meso-alert-postgres
  template:
    metadata:
      labels:
        app: meso-alert-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.2
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: meso-alert-postgres-password
                  key: password
                  optional: false
            - name: POSTGRES_DB
              value: "meso-alert"
            - name: POSTGRES_USER
              value: "meso-alert"
            - name: PGDATA
              value: "meso-alert"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: meso-alert-postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: meso-alert-postgres
  labels:
    app: meso-alert-postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      protocol: TCP
  selector:
    app: meso-alert-postgres
