apiVersion: v1
kind: Service
metadata:
  name: meso-alert-postgres
  labels:
    app: meso-alert-postgres
spec:
  type: NodePort
  ports:
   - port: 5432
     protocol: TCP
  selector:
   app: meso-alert-postgres
