apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meso-alert-postgres-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
