apiVersion: v1
kind: ConfigMap
metadata:
  name: meso-alert-postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: meso-alert
  POSTGRES_USER: meso-alert
  POSTGRES_PASSWORD: th0rnxtc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meso-alert-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meso-alert-postgres
  template:
    metadata:
      labels:
        app: meso-alert-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.2
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: meso-alert-postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: meso-alert-postgres-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: meso-alert-postgres-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/1/meso-alert"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meso-alert-postgres-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: meso-alert-postgres
  labels:
    app: meso-alert-postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      protocol: TCP
  selector:
    app: meso-alert-postgres
