apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: meso-alert-postgres-password
  namespace: default
spec:
  encryptedData:
    password: AgA79gzb+krAem5En+QOp4f9Ka9D3SKT9vEFJFaU3aLEU3W6oTZzlSHrwqGREsmdGQsZplksDGjQk4wW4NdLeOSbK9iLMtt8nMtdKIMZuP+2wqxDKABmUFO/hcnM+ZBN5rhWikmo4Rc3Yl33ntMegknqeMBy6ty0zp4224SKBSwSk7P+NYUZ2j4cch4CW2zKrEXM1D1b899HZ2+oR+CaXEbou7behrjYDe+foTU4vCWVxBuiogYeCnJ1pv9C0VEjwVVDniGo5wysr5PnaTM/dq2EtMtXFkWxuSMyqio7eJa1FbMDUm/hBYDKTyfCTYoUatncwC1wsnXcqsHuXfqSEpgGjfKjcXAnzaMf+CYjxGZSDAywaNOnu+y/YUb9Q0EKq7oJZjA0O8m44+UoQRm26HBo5/7IqWTJsOQYLOuTRTNV5XWOsC4YJgSwbQWDBCaAdrNLLvQL7gCfasVrzKiiYYX3Qak5amAaK6/0RpfdyGKk6m9XyC7C7rTScrTbmyZzc8DSsGxrEqne+Gm/s1FStuHFamDG7rI8SNT+0zViO27aptpgZydRd1M2QMFNF8oXXrbrTSJuTduGOF9CMYpz2mYEbBpcYLxRTQW2bhxh/dzxIA/0wMMogCnk9b14R7O7ypZOfVgFRVtXxM/gRT2nK9FgEjZ5CjqI1U+MLDGH6jDHD2LS02A5+gcvVlJ/rdMacbxHN3M4HHjWpQcyfDlDFec=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: meso-alert-postgres-password
      namespace: default

