apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: meso-alert
  name: meso-alert-service
spec:
  externalIPs:
  - 192.168.1.101
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: meso-alert
  type: NodePort
status:
  loadBalancer: {}
