
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meso-alert-deployment
  labels:
    app.kubernetes.io/name: meso-alert
spec:
  selector:
    matchLabels:
      app: meso-alert
  template:
    metadata:
      labels:
        app: meso-alert
    spec:
      containers:
        - name: meso-alert
          image: registry.gitlab.com/mesonomics/meso-alert/play-server:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 9000
              name: websocket
              protocol: TCP
          volumeMounts:
            - name: postgres-cred
              mountPath: "/etc/secrets/postgres"
              readOnly: true
            - name: play-secret
              mountPath: "/etc/secrets/play"
              readOnly: true
            - name: slack-secret
              mountPath: "/etc/secrets/slack"
              readOnly: true
            - name: sodium-secret
              mountPath: "/etc/secrets/sodium"
              readOnly: true
            - name: email-secret
              mountPath: "/etc/secrets/email"
              readOnly: true
            - name: auth0-secret
              mountPath: "/etc/secrets/auth0"
              readOnly: true
      volumes:
        - name: postgres-cred
          secret:
            secretName: meso-alert-postgres-password
        - name: play-secret
          secret:
            secretName: meso-alert-play-secret
        - name: slack-secret
          secret:
            secretName: meso-alert-slack
        - name: sodium-secret
          secret:
            secretName: meso-alert-sodium-secret
        - name: email-secret
          secret:
            secretName: meso-alert-email-secret
        - name: auth0-secret
          secret:
            secretName: meso-alert-auth0
      imagePullSecrets:
        - name: regcred
