apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: meso-alert
  name: meso-alert-service
spec:
  externalIPs:
  - 192.168.1.101
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: meso-alert
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meso-alert-deployment
  labels:
    app.kubernetes.io/name: meso-alert
spec:
  selector:
    matchLabels:
      app: meso-alert
  template:
    metadata:
      labels:
        app: meso-alert
    spec:
      containers:
        - name: meso-alert
          image: registry.gitlab.com/mesonomics/meso-alert/play-server:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 9000
              name: websocket
              protocol: TCP
      imagePullSecrets:
        - name: regcred
