apiVersion: v1
kind: PersistentVolume
metadata:
  name: meso-alert-postgres-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/1/meso-alert"
