apiVersion: v1
kind: PersistentVolume
metadata:
  name: meso-alert-postgres-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/1/meso-alert"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meso-alert-postgres-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
